no-console for frontend
trilogy-group/eslint-config pull request #15
Opened 2021-09-10 11:04 UTC by michal-grochowski

We need to enable no-console for our projects, as it is [not recommended](https://eslint.org/docs/rules/no-console#when-not-to-use-it) to use for Node.js applications it is addressing our need to have it on the frontend

2021-09-10 11:16 UTC, Tantalon requested changes

2021-09-10 11:16 UTC, Tantalon commented on index.js
> +            files: ['**/frontend/*.js', '**/frontend/*.ts'],
This won't include subfolders.
You'll need **/frontend/**/*.js and **/frontend/**/*.ts

2021-09-10 11:22 UTC, Tantalon commented
@CatalinAdlerDF the no-console rule has been scoped to frontend code based on the recommendation written in the eslint rule. Is this the same as DevCoach?

2021-09-10 11:22 UTC, CatalinAdlerDF commented
That rule should apply to any js/ts code.

2021-09-10 11:24 UTC, Tantalon commented
Why? That's not what it recommends. And CLI code and similar must use console output.

2021-09-10 11:25 UTC, michal-grochowski commented on index.js
> +            files: ['**/frontend/*.js', '**/frontend/*.ts'],
Hmm, my tests shows that it behaves the same, if you prefer me to add this let me know
![image](https://user-images.githubusercontent.com/31270013/132846393-60d6b060-cb12-42bc-89b6-28db1092ff71.png)

2021-09-10 11:30 UTC, michal-grochowski commented on index.js
> +            files: ['**/frontend/*.js', '**/frontend/*.ts'],
Addressed in https://github.com/trilogy-group/eslint-config/pull/15/commits/d8330a29368d66fab283c7e95d2e06bc4e12c75b

2021-09-10 11:31 UTC, Tantalon approved these changes

2021-09-13 06:58 UTC, CatalinAdlerDF commented
Because of code is code wherever it's executed and the reasons to not directly log to console span to backend as well.
You are confusing a log sink with a log system. Sinking logs to console might be ok for backend, using direct logging to console is not ok.

This is an antipattern in probably all languages used to write backends in bc the concerns ab how you log are the same. :)

2021-09-16 11:29 UTC, closed without merging